### ISSUE TITLE
Work on the backend to solve and clear the error

### ISSUE THREAD

**Issue by jaibhedia** [jaibhedia/NPB_VOTE_WEB3#2]
The backend has a bit of errors and is not functioning properly every time, so tune it to work and run properly.

**Comment by Touseef-md** [comment]
Hey @jaibhedia I would like to work on this. Please assign this to me.

**Comment by jaibhedia** [comment]
@Touseef-md I have assigned you the issue, please start working on it.

**Comment by NandishM0618** [comment]
@Touseef-md are you working on this issue right now?

**Comment by Touseef-md** [comment]
Yes, I'm working on this.

**Comment by NandishM0618** [comment]
@Touseef-md can I take on this issue now? Or you solved it?

**Comment by jaibhedia** [comment]
@Touseef-md Any progress?

**Comment by jaibhedia** [comment]
> @Touseef-md Any progress?

As you are not responding, I am adding @NandishM0618 as an assignee as well.
